Repository nextcloud/ansible-collection-nextcloud-admin, pull requests merged in 2023-08, with the labels that each got.

#297 Increase opcache.interned_strings_buffer
  roles/install_nextcloud/tasks/http_apache.yml
  roles/install_nextcloud/tasks/http_nginx.yml
Labels: bug

#292 Add possibility to use a downloaded nextcloud archive and copy on rem…
  roles/install_nextcloud/README.md
  roles/install_nextcloud/defaults/main.yml
  roles/install_nextcloud/tasks/nc_apps.yml
  roles/install_nextcloud/tasks/nc_download.yml
Labels: enhancement

#300 Fixes nginx conf file if using http (port 80) only
  roles/install_nextcloud/templates/nginx_nc.j2
Labels: bug

#304 Change role description
  galaxy.yml
Labels: documentation
