Repository nextcloud/ansible-collection-nextcloud-admin, pull requests merged in 2023-06, with the labels that each got.

#286 Fix broken Yamllint Github Action
  .github/workflows/ansible-lint.yml
  .github/workflows/constraints.txt
  .github/workflows/lint.yml
  .github/workflows/yamllint.yml
  README.md
  molecule/default/latest-converge.yml
Labels: ci

#280 Fix a bug in nc_apache2.j2 template concerning intermed-CA. Remove an…
  roles/install_nextcloud/tasks/tls_installed.yml
  roles/install_nextcloud/tasks/tls_signed.yml
  roles/install_nextcloud/templates/apache2_nc.j2
Labels: bug

#289 Version 2.1.0
  galaxy.yml
  roles/install_nextcloud/README.md
Labels: skip-changelog
