Repository nextcloud/ansible-collection-nextcloud-admin, pull requests merged in 2023-05, with the labels that each got.

#268 Add nextcloud backup role
  README.md
  requirements.yml
  roles/backup/README.md
  roles/backup/defaults/main.yml
  roles/backup/meta/main.yml
  roles/backup/tasks/app_data.yml
  roles/backup/tasks/database.yml
  roles/backup/tasks/fetching.yml
  roles/backup/tasks/files.yml
  roles/backup/tasks/finishing.yml
  roles/backup/tasks/main.yml
  roles/backup/tasks/nc_facts.yml
  roles/backup/tasks/user_data.yml
  roles/backup/vars/main.yml
  roles/install_nextcloud/README.md
Labels: enhancement, Feature

#271 Fix an issue with Ubuntu Server 23.04 where download form App-store i…
  roles/install_nextcloud/tasks/nc_apps.yml
Labels: bug

#276 Temporary ignore ansible-lint var-naming[no-role-prefix]
  .ansible-lint
Labels: ci
