Repository nextcloud/ansible-collection-nextcloud-admin, pull requests merged in 2023-01, with the labels that each got.

#193 remove tag always
  tasks/main.yml
Labels: refactoring

#195 Make nextcloud_websrv variable consistent in whole repo
  tasks/main.yml
  tasks/websrv_install.yml
Labels: refactoring

#188 Allow to disable preinstalled apps after installation
  README.md
  defaults/main.yml
  molecule/default/latest-converge.yml
  tasks/nc_installation.yml
  tests/nextcloud_mariadb.yml
  tests/nextcloud_mysql.yml
  tests/nextcloud_nginx.yml
  tests/nextcloud_psql.yml
Labels: Feature

#200 Bump version 1.8.0
  current-version.txt
Labels: skip-changelog
